Add a dependency check in clean-jpeg

diff --git a/bin/clean-jpeg b/bin/clean-jpeg
--- a/bin/clean-jpeg
+++ b/bin/clean-jpeg
@@ -13,4 +13,15 @@
 # @copyright 2015 Fabien Schurter
 #
 
+# Check that dependencies are installed
+exec_dependencies=( 'jpegoptim' )
+for exec in ${exec_dependencies[@]}; do
+  type $exec > /dev/null 2>&1
+  if [[ $? > 0 ]]; then
+    echo "Error: the '${exec}' program is required."
+    exit 1
+  fi
+done
+
+# Run
 jpegoptim -pt --strip-all $@
