Add some sanity checks in disable-spotlight

diff --git a/disable-spotlight b/disable-spotlight
--- a/disable-spotlight
+++ b/disable-spotlight
@@ -1,5 +1,22 @@
 #!/usr/bin/env bash
 
+# Check that dependencies are installed
+exec_dependencies=( 'mdutil' 'launchctl' )
+for exec in ${exec_dependencies[@]}; do
+  type $exec > /dev/null 2>&1
+  if [[ $? > 0 ]]; then
+    echo "Error: ${exec} is required. This script works on Mac OS X only."
+    exit 1
+  fi
+done
+
+# Check that current user is root
+if [[ $EUID != 0 ]]; then
+  echo 'Error: this script must be run as root.'
+  exit 1
+fi
+
+# Run
 mdutil -a -i off
 launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist
 chmod 0600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
